# Generated by Django 6.0.5 on 2026-05-13 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('organization_type', models.CharField(choices=[('private', 'Private Limited'), ('public', 'Public Limited'), ('nonprofit', 'Non-Profit'), ('government', 'Government'), ('partnership', 'Partnership'), ('sole_proprietorship', 'Sole Proprietorship')], default='private', max_length=30)),
                ('size', models.CharField(choices=[('micro', 'Micro (1-9)'), ('small', 'Small (10-49)'), ('medium', 'Medium (50-249)'), ('large', 'Large (250-999)'), ('enterprise', 'Enterprise (1000+)')], default='small', max_length=20)),
                ('founded_date', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='organization/favicons/')),
                ('primary_color', models.CharField(blank=True, help_text='Hex code e.g. #1A73E8', max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', help_text='ISO 4217 code', max_length=3)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=64)),
                ('fiscal_year_start', models.CharField(default='01-01', help_text='MM-DD', max_length=5)),
                ('weekly_working_days', models.PositiveSmallIntegerField(default=5)),
                ('weekly_working_hours', models.DecimalField(decimal_places=2, default=40, max_digits=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='The tenant organization for this deployment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ceo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_organizations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('branch_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('regional', 'Regional Office'), ('branch', 'Branch Office'), ('remote', 'Remote'), ('factory', 'Factory'), ('warehouse', 'Warehouse')], default='branch', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organization.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('policy', 'Policy'), ('handbook', 'Handbook'), ('contract', 'Contract'), ('license', 'License'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='organization/documents/')),
                ('description', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organization.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False, help_text='Repeats every year on the same MM-DD')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for org-wide holiday', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.organization')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('organization', 'branch', 'date', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('twitter', 'Twitter / X'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='organization.organization')),
            ],
            options={
                'unique_together': {('organization', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=60)),
                ('works_monday', models.BooleanField(default=True)),
                ('works_tuesday', models.BooleanField(default=True)),
                ('works_wednesday', models.BooleanField(default=True)),
                ('works_thursday', models.BooleanField(default=True)),
                ('works_friday', models.BooleanField(default=True)),
                ('works_saturday', models.BooleanField(default=False)),
                ('works_sunday', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='organization.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
